package cgg.tutorial.assignment;

import java.util.Date;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class CentreSave {

  public static void main(String[] args) {
    // Create a Hibernate configuration and build a SessionFactory
    Configuration configuration = new Configuration().configure();
    SessionFactory sessionFactory = configuration.buildSessionFactory();

    // Create a new session
    try (Session session = sessionFactory.openSession()) {
      // Begin a transaction
      session.beginTransaction();

      // Insert 5 records into CentreWiseOnlineRegistered
      for (int i = 1; i <= 5; i++) {
        CentreWiseOnlineRegistered record = createSampleRecord(i);
        session.persist(record);
      }

      // Commit the transaction
      session.getTransaction().commit();
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      // Close the session factory
      sessionFactory.close();
    }
  }

  // Helper method to create a sample record
  private static CentreWiseOnlineRegistered createSampleRecord(int index) {
    return new CentreWiseOnlineRegistered(
      // seqId will be generated by the database
      new Date(),
      index,
      100, // Example capacity value
      50, // Example registeredStudents value
      "Active",
      new Date(),
      123 + index, // Example passid value
      456 + index // Example mapId value
    );
  }
}
